name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: 26
          package-manager-cache: false

      - run: pnpm install

      - run: pnpm build

      - run: pnpm lint

      - run: pnpm format:check

      - run: pnpm test
